#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Removes all images, containers and volumes.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    echo "==Pruning images and containers..."
    docker system prune -af

    echo "==Pruning volumes..."
    docker volume rm $(docker volume ls) 2> /dev/null

    echo "Done!"
    echo ""

fi
