"""update item table

Revision ID: 16315389a78c
Revises: a55a3ebec204
Create Date: 2024-02-14 16:23:56.093564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16315389a78c"
down_revision = "a55a3ebec204"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("is_offer", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "is_offer")
    # ### end Alembic commands ###
